import "./globals.css";

/**
 * This acts as a _app.tsx file in old nextjs project

 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <h1>Root Layout</h1>
        {children}
      </body>
    </html>
  );
}
